export const JOB_POST_REQUEST = "USER_REGISTER_REQUEST";
export const JOB_POST_SUCCESS = "JOB_POST_SUCCESS";
export const JOB_POST_FAIL = "JOB_POST_FAIL";
export const JOB_POST_REST = "JOB_POST_REST";



export const GET_JOBLIST_REQUEST = "GET_JOBLIST_REQUEST";
export const GET_ALLJOB_SUCCESS = "GET_ALLJOB_SUCCESS";
export const GET_JOBLIST_FAIL = "GET_JOBLIST_FAIL";
export const GET_JOBLIST_REST = "GET_JOBLIST_REST";


export const JOB_EDIT_REQUEST = "JOB_EDIT_REQUEST";
export const JOB_EDIT_SUCCESS = "JOB_EDIT_SUCCESS";
export const JOB_EDIT_FAIL = "JOB_EDIT_FAIL";


export const GET_SINGLEJOB_REQUEST = "GET_SINGLEJOB_REQUEST";
export const GET_SINGLE_JOB_SUCCESS = "GET_SINGLE_JOB_SUCCESS";
export const GET_SINGLE_JOB_FAIL = "GET_SINGLE_JOB_FAIL";

export const REST_SINGLEJOB = "REST_SINGLEJOB";

export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAIL = "JOB_DELETE_FAIL";
