export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAIL = "APPLY_JOB_FAIL";
export const APPLY_JOB_REST = "APPLY_JOB_REST";

export const APPLIED_JOBLIST_REQUEST = "APPLIED_JOBLIST_REQUEST";
export const APPLIED_JOBLIST_SUCCESS = "APPLIED_JOBLIST_SUCCESS";
export const APPLIED_JOBLIST_FAIL = "APPLY_JOBLIST_FAIL";
export const APPLY_JOBLIST_REST = "APPLY_JOBLIST_REST";

export const APPLIED_JOB_UPDATE_REQUEST = "APPLIED_JOB_UPDATE_REQUEST";
export const APPLIED_JOB_UPDATE_SUCCESS = "APPLIED_JOB_UPDATE_SUCCESS";
export const APPLIED_JOB_UPDATE_FAIL = "APPLIED_JOB_UPDATE_FAIL";

export const DELETE_APPLIED_JOB_REQUEST = "DELETE_APPLIED_JOB_REQUEST";
export const DELETE_APPLIED_JOB_SUCCESS = "DELETE_APPLIED_JOB_SUCCESS";
export const DELETE_APPLIED_JOB_FAIL = "DELETE_APPLIED_JOB_FAIL";
export const DELETE_JOBLIST_REST = "DELETE_JOBLIST_REST";